# Translation map: English value -> Persian translation
# This covers all 422 untranslated values in config-global.json
$translations = @{
    # version
    "Numeric or string version of the active configuration to help detect migrations or format changes." = "نسخه عددی یا رشته‌ای پیکربندی فعال برای کمک به تشخیص مهاجرت‌ها یا تغییرات قالب."
    # safe_mode
    "When enabled, start Frigate in safe mode with reduced features for troubleshooting." = "در صورت فعال بودن، فریگیت در حالت امن با ویژگی‌های کاهش‌یافته برای رفع اشکال راه‌اندازی می‌شود."
    # environment_vars
    "Key/value pairs of environment variables to set for the Frigate process in Home Assistant OS. Non-HAOS users must use Docker environment variable configuration instead." = "جفت‌های کلید/مقدار متغیرهای محیطی برای تنظیم فرآیند فریگیت در Home Assistant OS. کاربران غیر HAOS باید از پیکربندی متغیرهای محیطی Docker استفاده کنند."
    # logger
    "Controls default log verbosity and per-component log level overrides." = "سطح گزارش‌گیری پیش‌فرض و لغوهای سطح گزارش هر مؤلفه را کنترل می‌کند."
    "Default global log verbosity (debug, info, warning, error)." = "سطح گزارش‌گیری سراسری پیش‌فرض (debug، info، warning، error)."
    "Per-process log level" = "سطح گزارش هر فرآیند"
    "Per-component log level overrides to increase or decrease verbosity for specific modules." = "لغوهای سطح گزارش هر مؤلفه برای افزایش یا کاهش سطح تفصیل ماژول‌های خاص."
    # auth
    "Authentication and session-related settings including cookie and rate limit options." = "تنظیمات احراز هویت و نشست شامل گزینه‌های کوکی و محدودیت نرخ."
    "Enable native authentication for the Frigate UI." = "احراز هویت بومی رابط کاربری فریگیت را فعال کنید."
    "If true, reset the admin user's password on startup and print the new password in logs." = "اگر درست باشد، رمز کاربر مدیر در هنگام راه‌اندازی بازنشانی شده و رمز جدید در گزارش‌ها چاپ می‌شود."
    "JWT cookie name" = "نام کوکی JWT"
    "Name of the cookie used to store the JWT token for native authentication." = "نام کوکی مورد استفاده برای ذخیره توکن JWT برای احراز هویت بومی."
    "Secure cookie flag" = "پرچم امن کوکی"
    "Set the secure flag on the auth cookie; should be true when using TLS." = "پرچم امن را روی کوکی احراز هویت تنظیم کنید؛ هنگام استفاده از TLS باید درست باشد."
    "Session length" = "مدت نشست"
    "Session duration in seconds for JWT-based sessions." = "مدت زمان نشست بر حسب ثانیه برای نشست‌های مبتنی بر JWT."
    "Session refresh window" = "پنجره بازنشانی نشست"
    "When a session is within this many seconds of expiring, refresh it back to full length." = "وقتی یک نشست در این تعداد ثانیه از انقضا باشد، آن را به مدت کامل بازنشانی کنید."
    "Failed login limits" = "محدودیت‌های ورود ناموفق"
    "Rate limiting rules for failed login attempts to reduce brute-force attacks." = "قوانین محدودیت نرخ برای تلاش‌های ورود ناموفق جهت کاهش حملات brute-force."
    "List of trusted proxy IPs used when determining client IP for rate limiting." = "فهرست IPهای پراکسی مورد اعتماد که برای تعیین IP کلاینت در محدودیت نرخ استفاده می‌شوند."
    "Hash iterations" = "تعداد تکرار هش"
    "Number of PBKDF2-SHA256 iterations to use when hashing user passwords." = "تعداد تکرارهای PBKDF2-SHA256 برای استفاده هنگام هش کردن رمزهای کاربر."
    "Role mappings" = "نگاشت نقش‌ها"
    "Map roles to camera lists. An empty list grants access to all cameras for the role." = "نگاشت نقش‌ها به فهرست دوربین‌ها. یک فهرست خالی دسترسی به همه دوربین‌ها را برای نقش فراهم می‌کند."
    "First-time admin flag" = "پرچم مدیر اولین‌بار"
    "When true the UI may show a help link on the login page informing users how to sign in after an admin password reset. " = "در صورت درست بودن، رابط کاربری ممکن است یک پیوند راهنما در صفحه ورود نشان دهد که کاربران را از نحوه ورود پس از بازنشانی رمز مدیر آگاه می‌کند."
    # database
    "Settings for the SQLite database used by Frigate to store tracked object and recording metadata." = "تنظیمات پایگاه داده SQLite مورد استفاده فریگیت برای ذخیره فراداده اشیاء ردیابی‌شده و ضبط‌ها."
    "Database path" = "مسیر پایگاه داده"
    "Filesystem path where the Frigate SQLite database file will be stored." = "مسیر سیستم فایل که فایل پایگاه داده SQLite فریگیت در آن ذخیره می‌شود."
    # go2rtc
    "Settings for the integrated go2rtc restreaming service used for live stream relaying and translation." = "تنظیمات سرویس go2rtc یکپارچه برای پخش مجدد زنده و ترجمه جریان."
    # mqtt
    "Settings for connecting and publishing telemetry, snapshots, and event details to an MQTT broker." = "تنظیمات اتصال و انتشار تلمتری، عکس‌های فوری و جزئیات رویداد به یک بروکر MQTT."
    "Enable MQTT" = "فعال کردن MQTT"
    "Enable or disable MQTT integration for state, events, and snapshots." = "فعال یا غیرفعال کردن یکپارچه‌سازی MQTT برای وضعیت، رویدادها و عکس‌های فوری."
    "MQTT host" = "میزبان MQTT"
    "Hostname or IP address of the MQTT broker." = "نام میزبان یا آدرس IP بروکر MQTT."
    "MQTT port" = "پورت MQTT"
    "Port of the MQTT broker (usually 1883 for plain MQTT)." = "پورت بروکر MQTT (معمولاً 1883 برای MQTT ساده)."
    "Topic prefix" = "پیشوند موضوع"
    "MQTT topic prefix for all Frigate topics; must be unique if running multiple instances." = "پیشوند موضوع MQTT برای همه موضوعات فریگیت؛ در صورت اجرای چندین نمونه باید یکتا باشد."
    "Client ID" = "شناسه کلاینت"
    "Client identifier used when connecting to the MQTT broker; should be unique per instance." = "شناسه کلاینت مورد استفاده هنگام اتصال به بروکر MQTT؛ باید به ازای هر نمونه یکتا باشد."
    "Stats interval" = "بازه آمار"
    "Interval in seconds for publishing system and camera stats to MQTT." = "بازه بر حسب ثانیه برای انتشار آمار سیستم و دوربین به MQTT."
    "MQTT username" = "نام کاربری MQTT"
    "Optional MQTT username; can be provided via environment variables or secrets." = "نام کاربری اختیاری MQTT؛ می‌تواند از طریق متغیرهای محیطی یا اسرار ارائه شود."
    "MQTT password" = "رمز عبور MQTT"
    "Optional MQTT password; can be provided via environment variables or secrets." = "رمز عبور اختیاری MQTT؛ می‌تواند از طریق متغیرهای محیطی یا اسرار ارائه شود."
    "TLS CA certs" = "گواهی‌های CA برای TLS"
    "Path to CA certificate for TLS connections to the broker (for self-signed certs)." = "مسیر گواهی CA برای اتصالات TLS به بروکر (برای گواهی‌های خودامضا)."
    "Client cert" = "گواهی کلاینت"
    "Client certificate path for TLS mutual authentication; do not set user/password when using client certs." = "مسیر گواهی کلاینت برای احراز هویت متقابل TLS؛ هنگام استفاده از گواهی کلاینت، نام کاربری/رمز عبور تنظیم نکنید."
    "Client key" = "کلید کلاینت"
    "Private key path for the client certificate." = "مسیر کلید خصوصی برای گواهی کلاینت."
    "TLS insecure" = "TLS ناامن"
    "Allow insecure TLS connections by skipping hostname verification (not recommended)." = "اجازه اتصالات TLS ناامن با نادیده گرفتن تأیید نام میزبان (توصیه نمی‌شود)."
    "MQTT QoS" = "QoS مربوط به MQTT"
    "Quality of Service level for MQTT publishes/subscriptions (0, 1, or 2)." = "سطح کیفیت سرویس برای انتشار/اشتراک MQTT (0، 1 یا 2)."
    # notifications
    "Settings to enable and control notifications for all cameras; can be overridden per-camera." = "تنظیمات فعال‌سازی و کنترل اعلان‌ها برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    "Enable or disable notifications for all cameras; can be overridden per-camera." = "فعال یا غیرفعال کردن اعلان‌ها برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    # networking
    "Networking" = "شبکه‌بندی"
    "Network-related settings such as IPv6 enablement for Frigate endpoints." = "تنظیمات مرتبط با شبکه مانند فعال‌سازی IPv6 برای نقاط پایانی فریگیت."
    "IPv6 configuration" = "پیکربندی IPv6"
    "IPv6-specific settings for Frigate network services." = "تنظیمات خاص IPv6 برای سرویس‌های شبکه فریگیت."
    "Enable IPv6" = "فعال کردن IPv6"
    "Enable IPv6 support for Frigate services (API and UI) where applicable." = "فعال‌سازی پشتیبانی IPv6 برای سرویس‌های فریگیت (API و رابط کاربری) در صورت وجود."
    "Listening ports configuration" = "پیکربندی پورت‌های شنود"
    "Configuration for internal and external listening ports. This is for advanced users. For the majority of use cases it's recommended to change the ports section of your Docker compose file." = "پیکربندی پورت‌های شنود داخلی و خارجی. این برای کاربران پیشرفته است. برای اکثر موارد استفاده، توصیه می‌شود بخش پورت‌های فایل Docker compose خود را تغییر دهید."
    "Internal port" = "پورت داخلی"
    "Internal listening port for Frigate (default 5000)." = "پورت شنود داخلی فریگیت (پیش‌فرض 5000)."
    "External port" = "پورت خارجی"
    "External listening port for Frigate (default 8971)." = "پورت شنود خارجی فریگیت (پیش‌فرض 8971)."
    # proxy
    "Proxy" = "پروکسی"
    "Settings for integrating Frigate behind a reverse proxy that passes authenticated user headers." = "تنظیمات یکپارچه‌سازی فریگیت پشت یک پروکسی معکوس که هدرهای کاربر احراز هویت‌شده را ارسال می‌کند."
    "Header mapping" = "نگاشت هدر"
    "Map incoming proxy headers to Frigate user and role fields for proxy-based auth." = "نگاشت هدرهای پروکسی ورودی به فیلدهای کاربر و نقش فریگیت برای احراز هویت مبتنی بر پروکسی."
    "User header" = "هدر کاربر"
    "Header containing the authenticated username provided by the upstream proxy." = "هدر حاوی نام کاربری احراز هویت‌شده ارائه‌شده توسط پروکسی بالادستی."
    "Role header" = "هدر نقش"
    "Header containing the authenticated user's role or groups from the upstream proxy." = "هدر حاوی نقش یا گروه‌های کاربر احراز هویت‌شده از پروکسی بالادستی."
    "Role mapping" = "نگاشت نقش"
    "Map upstream group values to Frigate roles (for example map admin groups to the admin role)." = "نگاشت مقادیر گروه بالادستی به نقش‌های فریگیت (مثلاً نگاشت گروه‌های مدیر به نقش مدیر)."
    "Logout URL" = "آدرس خروج"
    "URL to redirect users to when logging out via the proxy." = "آدرس برای هدایت کاربران هنگام خروج از طریق پروکسی."
    "Proxy secret" = "رمز پروکسی"
    "Optional secret checked against the X-Proxy-Secret header to verify trusted proxies." = "رمز اختیاری که در برابر هدر X-Proxy-Secret بررسی می‌شود تا پروکسی‌های مورد اعتماد تأیید شوند."
    "Default role" = "نقش پیش‌فرض"
    "Default role assigned to proxy-authenticated users when no role mapping applies." = "نقش پیش‌فرض اختصاص‌یافته به کاربران احراز هویت‌شده توسط پروکسی وقتی هیچ نگاشت نقشی اعمال نمی‌شود."
    "Separator character" = "نویسه جداکننده"
    "Character used to split multiple values provided in proxy headers." = "نویسه مورد استفاده برای تفکیک مقادیر چندگانه ارائه‌شده در هدرهای پروکسی."
    # telemetry
    "Telemetry" = "تلمتری"
    "System telemetry and stats options including GPU and network bandwidth monitoring." = "گزینه‌های تلمتری و آمار سیستم شامل پایش GPU و پهنای باند شبکه."
    "Network interfaces" = "رابط‌های شبکه"
    "List of network interface name prefixes to monitor for bandwidth statistics." = "فهرست پیشوندهای نام رابط شبکه برای پایش آمار پهنای باند."
    "System stats" = "آمار سیستم"
    "Options to enable/disable collection of various system and GPU statistics." = "گزینه‌هایی برای فعال/غیرفعال کردن جمع‌آوری آمارهای مختلف سیستم و GPU."
    "AMD GPU stats" = "آمار GPU ای‌ام‌دی"
    "Enable collection of AMD GPU statistics if an AMD GPU is present." = "فعال‌سازی جمع‌آوری آمار GPU AMD در صورت وجود GPU AMD."
    "Intel GPU stats" = "آمار GPU اینتل"
    "Enable collection of Intel GPU statistics if an Intel GPU is present." = "فعال‌سازی جمع‌آوری آمار GPU اینتل در صورت وجود GPU اینتل."
    "Network bandwidth" = "پهنای باند شبکه"
    "Enable per-process network bandwidth monitoring for camera ffmpeg processes and detectors (requires capabilities)." = "فعال‌سازی پایش پهنای باند شبکه به ازای هر فرآیند برای فرآیندهای ffmpeg دوربین و آشکارسازها (نیازمند قابلیت‌ها)."
    "Intel GPU device" = "دستگاه GPU اینتل"
    "PCI bus address or DRM device path (e.g. /dev/dri/card1) used to pin Intel GPU stats to a specific device when multiple are present." = "آدرس باس PCI یا مسیر دستگاه DRM (مثلاً /dev/dri/card1) که برای پین کردن آمار GPU اینتل به دستگاه خاصی هنگام وجود چند دستگاه استفاده می‌شود."
    "Version check" = "بررسی نسخه"
    "Enable an outbound check to detect if a newer Frigate version is available." = "فعال‌سازی یک بررسی خروجی برای تشخیص در دسترس بودن نسخه جدیدتر فریگیت."
    # tls
    "TLS" = "TLS"
    "TLS settings for Frigate's web endpoints (port 8971)." = "تنظیمات TLS برای نقاط پایانی وب فریگیت (پورت 8971)."
    "Enable TLS" = "فعال کردن TLS"
    "Enable TLS for Frigate's web UI and API on the configured TLS port." = "فعال‌سازی TLS برای رابط کاربری وب و API فریگیت روی پورت TLS پیکربندی‌شده."
    # ui
    "UI" = "رابط کاربری"
    "User interface preferences such as timezone, time/date formatting, and units." = "ترجیحات رابط کاربری مانند منطقه زمانی، قالب‌بندی زمان/تاریخ و واحدها."
    "Timezone" = "منطقه زمانی"
    "Optional timezone to display across the UI (defaults to browser local time if unset)." = "منطقه زمانی اختیاری برای نمایش در رابط کاربری (پیش‌فرض زمان محلی مرورگر در صورت تنظیم نشدن)."
    "Time format" = "قالب زمان"
    "Time format to use in the UI (browser, 12hour, or 24hour)." = "قالب زمان برای استفاده در رابط کاربری (مرورگر، 12 ساعته یا 24 ساعته)."
    "Unit system" = "سیستم واحدها"
    "Unit system for display (metric or imperial) used in the UI and MQTT." = "سیستم واحدها برای نمایش (متریک یا امپریال) استفاده‌شده در رابط کاربری و MQTT."
    # detectors
    "Detector hardware" = "سخت‌افزار آشکارساز"
    "Configuration for object detectors (CPU, GPU, ONNX backends) and any detector-specific model settings." = "پیکربندی آشکارسازهای اشیاء (CPU، GPU، پس‌زمینه‌های ONNX) و تنظیمات مدل خاص آشکارساز."
    "Type" = "نوع"
    "Detector specific model configuration" = "پیکربندی مدل خاص آشکارساز"
    "Detector-specific model configuration options (path, input size, etc.)." = "گزینه‌های پیکربندی مدل خاص آشکارساز (مسیر، اندازه ورودی و غیره)."
    "Custom object detector model path" = "مسیر مدل آشکارساز اشیاء سفارشی"
    "Path to a custom detection model file (or plus://<model_id> for Frigate+ models)." = "مسیر فایل مدل تشخیص سفارشی (یا plus://<model_id> برای مدل‌های Frigate+)."
    "Label map for custom object detector" = "نقشه برچسب برای آشکارساز اشیاء سفارشی"
    "Path to a labelmap file that maps numeric classes to string labels for the detector." = "مسیر فایل نقشه برچسب که کلاس‌های عددی را به برچسب‌های رشته‌ای برای آشکارساز نگاشت می‌کند."
    "Object detection model input width" = "عرض ورودی مدل تشخیص اشیاء"
    "Width of the model input tensor in pixels." = "عرض تنسور ورودی مدل بر حسب پیکسل."
    "Object detection model input height" = "ارتفاع ورودی مدل تشخیص اشیاء"
    "Height of the model input tensor in pixels." = "ارتفاع تنسور ورودی مدل بر حسب پیکسل."
    "Labelmap customization" = "سفارشی‌سازی نقشه برچسب"
    "Overrides or remapping entries to merge into the standard labelmap." = "ورودی‌های لغو یا نگاشت مجدد برای ادغام در نقشه برچسب استاندارد."
    "Map of object labels to their attribute labels" = "نگاشت برچسب‌های اشیاء به برچسب‌های ویژگی‌هایشان"
    "Mapping from object labels to attribute labels used to attach metadata (for example 'car' -> ['license_plate'])." = "نگاشت از برچسب‌های اشیاء به برچسب‌های ویژگی برای پیوست فراداده (مثلاً 'car' -> ['license_plate'])."
    "Model Input Tensor Shape" = "شکل تنسور ورودی مدل"
    "Tensor format expected by the model: 'nhwc' or 'nchw'." = "قالب تنسور مورد انتظار مدل: 'nhwc' یا 'nchw'."
    "Model Input Pixel Color Format" = "قالب رنگ پیکسل ورودی مدل"
    "Pixel colorspace expected by the model: 'rgb', 'bgr', or 'yuv'." = "فضای رنگ پیکسل مورد انتظار مدل: 'rgb'، 'bgr' یا 'yuv'."
    "Model Input D Type" = "نوع داده ورودی مدل"
    "Data type of the model input tensor (for example 'float32')." = "نوع داده تنسور ورودی مدل (مثلاً 'float32')."
    "Object Detection Model Type" = "نوع مدل تشخیص اشیاء"
    "Detector model architecture type (ssd, yolox, yolonas, yolo-generic, rfdetr, dfine) used by some detectors for optimization." = "نوع معماری مدل آشکارساز (ssd، yolox، yolonas، yolo-generic، rfdetr، dfine) که توسط برخی آشکارسازها برای بهینه‌سازی استفاده می‌شود."
    "Detector specific model path" = "مسیر مدل خاص آشکارساز"
    "File path to the detector model binary if required by the chosen detector." = "مسیر فایل باینری مدل آشکارساز در صورت نیاز توسط آشکارساز انتخاب‌شده."
    "AXEngine NPU" = "NPU با موتور AXEngine"
    "AXERA AX650N/AX8850N NPU detector running compiled .axmodel files via the AXEngine runtime." = "آشکارساز NPU ایکس‌اِرا AX650N/AX8850N که فایل‌های .axmodel کامپایل‌شده را از طریق زمان اجرای AXEngine اجرا می‌کند."
    "CPU" = "CPU"
    "CPU TFLite detector that runs TensorFlow Lite models on the host CPU without hardware acceleration. Not recommended." = "آشکارساز TFLite پردازنده که مدل‌های TensorFlow Lite را روی CPU میزبان بدون شتاب سخت‌افزاری اجرا می‌کند. توصیه نمی‌شود."
    "Number of detection threads" = "تعداد رشته‌های تشخیص"
    "The number of threads used for CPU-based inference." = "تعداد رشته‌های مورد استفاده برای استنتاج مبتنی بر CPU."
    "DeepStack" = "DeepStack"
    "DeepStack/CodeProject.AI detector that sends images to a remote DeepStack HTTP API for inference. Not recommended." = "آشکارساز DeepStack/CodeProject.AI که تصاویر را به یک API از راه دور DeepStack برای استنتاج ارسال می‌کند. توصیه نمی‌شود."
    "DeepStack API URL" = "آدرس API دیپ‌استک"
    "The URL of the DeepStack API." = "آدرس API دیپ‌استک."
    "DeepStack API timeout (in seconds)" = "زمان انقضای API دیپ‌استک (به ثانیه)"
    "Maximum time allowed for a DeepStack API request." = "حداکثر زمان مجاز برای درخواست API دیپ‌استک."
    "DeepStack API key (if required)" = "کلید API دیپ‌استک (در صورت نیاز)"
    "Optional API key for authenticated DeepStack services." = "کلید API اختیاری برای سرویس‌های احراز هویت‌شده DeepStack."
    "EdgeTPU" = "EdgeTPU"
    "EdgeTPU detector that runs TensorFlow Lite models compiled for Coral EdgeTPU using the EdgeTPU delegate." = "آشکارساز EdgeTPU که مدل‌های TensorFlow Lite کامپایل‌شده برای Coral EdgeTPU را با استفاده از delegate EdgeTPU اجرا می‌کند."
    "Device Type" = "نوع دستگاه"
    "The device to use for EdgeTPU inference (e.g. 'usb', 'pci')." = "دستگاه مورد استفاده برای استنتاج EdgeTPU (مثلاً 'usb'، 'pci')."
    "Hailo-8/Hailo-8L" = "Hailo-8/Hailo-8L"
    "Hailo-8/Hailo-8L detector using HEF models and the HailoRT SDK for inference on Hailo hardware." = "آشکارساز Hailo-8/Hailo-8L که از مدل‌های HEF و SDK هیلو‌آر‌تی برای استنتاج روی سخت‌افزار Hailo استفاده می‌کند."
    "The device to use for Hailo inference (e.g. 'PCIe', 'M.2')." = "دستگاه مورد استفاده برای استنتاج Hailo (مثلاً 'PCIe'، 'M.2')."
    "MemryX" = "MemryX"
    "MemryX MX3 detector that runs compiled DFP models on MemryX accelerators." = "آشکارساز MemryX MX3 که مدل‌های DFP کامپایل‌شده را روی شتاب‌دهنده‌های MemryX اجرا می‌کند."
    "Device Path" = "مسیر دستگاه"
    "The device to use for MemryX inference (e.g. 'PCIe')." = "دستگاه مورد استفاده برای استنتاج MemryX (مثلاً 'PCIe')."
    "ONNX" = "ONNX"
    "ONNX detector for running ONNX models; will use available acceleration backends (CUDA/ROCm/OpenVINO) when available." = "آشکارساز ONNX برای اجرای مدل‌های ONNX؛ از پس‌زمینه‌های شتاب‌دهی موجود (CUDA/ROCm/OpenVINO) در صورت وجود استفاده می‌کند."
    "The device to use for ONNX inference (e.g. 'AUTO', 'CPU', 'GPU')." = "دستگاه مورد استفاده برای استنتاج ONNX (مثلاً 'AUTO'، 'CPU'، 'GPU')."
    "OpenVINO" = "OpenVINO"
    "OpenVINO detector for AMD and Intel CPUs, Intel GPUs and Intel VPU hardware." = "آشکارساز OpenVINO برای پردازنده‌های AMD و اینتل، GPUهای اینتل و سخت‌افزار VPU اینتل."
    "The device to use for OpenVINO inference (e.g. 'CPU', 'GPU', 'NPU')." = "دستگاه مورد استفاده برای استنتاج OpenVINO (مثلاً 'CPU'، 'GPU'، 'NPU')."
    "RKNN" = "RKNN"
    "RKNN detector for Rockchip NPUs; runs compiled RKNN models on Rockchip hardware." = "آشکارساز RKNN برای NPUهای راک‌چیپ؛ مدل‌های RKNN کامپایل‌شده را روی سخت‌افزار راک‌چیپ اجرا می‌کند."
    "Number of NPU cores to use." = "تعداد هسته‌های NPU برای استفاده."
    "The number of NPU cores to use (0 for auto)." = "تعداد هسته‌های NPU برای استفاده (0 برای خودکار)."
    "Synaptics" = "سیناپتیکس"
    "Synaptics NPU detector for models in .synap format using the Synap SDK on Synaptics hardware." = "آشکارساز NPU سیناپتیکس برای مدل‌های با قالب .synap با استفاده از SDK سیناپ روی سخت‌افزار سیناپتیکس."
    "Teflon" = "تفلون"
    "Teflon delegate detector for TFLite using Mesa Teflon delegate library to accelerate inference on supported GPUs." = "آشکارساز delegate تفلون برای TFLite با استفاده از کتابخانه delegate تفلون Mesa برای شتاب‌دهی استنتاج روی GPUهای پشتیبانی‌شده."
    "TensorRT" = "TensorRT"
    "TensorRT detector for Nvidia Jetson devices using serialized TensorRT engines for accelerated inference." = "آشکارساز TensorRT برای دستگاه‌های Nvidia Jetson با استفاده از موتورهای TensorRT سری‌سازی‌شده برای استنتاج شتاب‌دهی‌شده."
    "GPU Device Index" = "شاخص دستگاه GPU"
    "The GPU device index to use." = "شاخص دستگاه GPU برای استفاده."
    "ZMQ IPC" = "ZMQ IPC"
    "ZMQ IPC detector that offloads inference to an external process via a ZeroMQ IPC endpoint." = "آشکارساز ZMQ IPC که استنتاج را به یک فرآیند خارجی از طریق یک نقطه پایانی ZeroMQ IPC تخلیه می‌کند."
    "ZMQ IPC endpoint" = "نقطه پایانی ZMQ IPC"
    "The ZMQ endpoint to connect to." = "نقطه پایانی ZMQ برای اتصال."
    "ZMQ request timeout in milliseconds" = "زمان انقضای درخواست ZMQ بر حسب میلی‌ثانیه"
    "Timeout for ZMQ requests in milliseconds." = "زمان انقضای درخواست‌های ZMQ بر حسب میلی‌ثانیه."
    "ZMQ socket linger in milliseconds" = "ماندن سوکت ZMQ بر حسب میلی‌ثانیه"
    "Socket linger period in milliseconds." = "دوره ماندن سوکت بر حسب میلی‌ثانیه."
    # model
    "Detection model" = "مدل تشخیص"
    "Settings to configure a custom object detection model and its input shape." = "تنظیمات برای پیکربندی یک مدل تشخیص اشیاء سفارشی و شکل ورودی آن."
    # genai
    "Generative AI configuration" = "پیکربندی هوش مصنوعی مولد"
    "Settings for integrated generative AI providers used to generate object descriptions and review summaries." = "تنظیمات ارائه‌دهندگان هوش مصنوعی مولد یکپارچه برای تولید توضیحات اشیاء و خلاصه‌های بازبینی."
    "API key" = "کلید API"
    "API key required by some providers (can also be set via environment variables)." = "کلید API مورد نیاز برخی ارائه‌دهندگان (همچنین قابل تنظیم از طریق متغیرهای محیطی)."
    "Base URL" = "آدرس پایه"
    "Base URL for self-hosted or compatible providers (for example an Ollama instance)." = "آدرس پایه برای ارائه‌دهندگان خودمیزبان یا سازگار (مثلاً یک نمونه Ollama)."
    "Model" = "مدل"
    "The model to use from the provider for generating descriptions or summaries." = "مدل مورد استفاده از ارائه‌دهنده برای تولید توضیحات یا خلاصه‌ها."
    "Provider" = "ارائه‌دهنده"
    "The GenAI provider to use (for example: ollama, gemini, openai)." = "ارائه‌دهنده GenAI برای استفاده (مثلاً: ollama، gemini، openai)."
    "Roles" = "نقش‌ها"
    "GenAI roles (chat, descriptions, embeddings); one provider per role." = "نقش‌های GenAI (گفتگو، توضیحات، جاسازی‌ها)؛ یک ارائه‌دهنده به ازای هر نقش."
    "Provider options" = "گزینه‌های ارائه‌دهنده"
    "Additional provider-specific options to pass to the GenAI client." = "گزینه‌های اضافی خاص ارائه‌دهنده برای ارسال به کلاینت GenAI."
    "Runtime options" = "گزینه‌های زمان اجرا"
    "Runtime options passed to the provider for each inference call." = "گزینه‌های زمان اجرا ارسال‌شده به ارائه‌دهنده برای هر فراخوانی استنتاج."
    # audio
    "Enable or disable audio event detection for all cameras; can be overridden per-camera." = "فعال یا غیرفعال کردن تشخیص رویداد صوتی برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    "Minimum audio confidence" = "حداقل اطمینان صوتی"
    "Minimum confidence threshold for the audio event to be counted." = "حداقل آستانه اطمینان برای رویداد صوتی تا شمارش شود."
    # birdseye
    "Restream RTSP" = "بازپخش RTSP"
    "Re-stream the Birdseye output as an RTSP feed; enabling this will keep Birdseye running continuously." = "بازپخش خروجی چشم پرنده به‌عنوان یک جریان RTSP؛ فعال‌سازی این گزینه چشم پرنده را به‌طور پیوسته در حال اجرا نگه می‌دارد."
    "Width" = "عرض"
    "Output width (pixels) of the composed Birdseye frame." = "عرض خروجی (پیکسل) فریم ترکیب‌شده چشم پرنده."
    "Height" = "ارتفاع"
    "Output height (pixels) of the composed Birdseye frame." = "ارتفاع خروجی (پیکسل) فریم ترکیب‌شده چشم پرنده."
    "Encoding quality" = "کیفیت کدگذاری"
    "Encoding quality for the Birdseye mpeg1 feed (1 highest quality, 31 lowest)." = "کیفیت کدگذاری برای جریان mpeg1 چشم پرنده (1 بالاترین کیفیت، 31 پایین‌ترین)."
    "Inactivity threshold" = "آستانه عدم فعالیت"
    "Seconds of inactivity after which a camera will stop being shown in Birdseye." = "ثانیه‌های عدم فعالیت که پس از آن یک دوربین در چشم پرنده نمایش داده نمی‌شود."
    "Layout" = "چیدمان"
    "Layout options for the Birdseye composition." = "گزینه‌های چیدمان برای ترکیب چشم پرنده."
    "Scaling factor" = "ضریب مقیاس"
    "Scaling factor used by the layout calculator (range 1.0 to 5.0)." = "ضریب مقیاس مورد استفاده توسط محاسبه‌گر چیدمان (محدوده 1.0 تا 5.0)."
    "Max cameras" = "حداکثر دوربین‌ها"
    "Maximum number of cameras to display at once in Birdseye; shows the most recent cameras." = "حداکثر تعداد دوربین‌ها برای نمایش همزمان در چشم پرنده؛ دوربین‌های اخیر را نشان می‌دهد."
    "Idle heartbeat FPS" = "FPS ضربان قلب بیکار"
    "Frames-per-second to resend the last composed Birdseye frame when idle; set to 0 to disable." = "فریم بر ثانیه برای ارسال مجدد آخرین فریم ترکیب‌شده چشم پرنده در حالت بیکار؛ 0 برای غیرفعال‌سازی."
    # detect
    "Enable or disable object detection for all cameras; can be overridden per-camera." = "فعال یا غیرفعال کردن تشخیص اشیاء برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    # live
    "Settings to control the jsmpeg live stream resolution and quality. This does not affect restreamed cameras that use go2rtc for live view." = "تنظیمات کنترل وضوح و کیفیت جریان زنده jsmpeg. این روی دوربین‌های بازپخش‌شده که از go2rtc برای نمای زنده استفاده می‌کنند تأثیری ندارد."
    # motion
    "Default motion detection settings applied to cameras unless overridden per-camera." = "تنظیمات پیش‌فرض تشخیص حرکت اعمال‌شده روی دوربین‌ها مگر اینکه به ازای هر دوربین لغو شود."
    "Enable or disable motion detection for all cameras; can be overridden per-camera." = "فعال یا غیرفعال کردن تشخیص حرکت برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    # objects
    "List of object labels to track for all cameras; can be overridden per-camera." = "فهرست برچسب‌های اشیاء برای ردیابی در همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    # record
    "Recording and retention settings applied to cameras unless overridden per-camera." = "تنظیمات ضبط و نگهداری اعمال‌شده روی دوربین‌ها مگر اینکه به ازای هر دوربین لغو شود."
    "Enable or disable recording for all cameras; can be overridden per-camera." = "فعال یا غیرفعال کردن ضبط برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    # review
    "Settings that control alerts, detections, and GenAI review summaries used by the UI and storage." = "تنظیماتی که هشدارها، تشخیص‌ها و خلاصه‌های بازبینی GenAI مورد استفاده رابط کاربری و ذخیره‌سازی را کنترل می‌کنند."
    "Enable or disable alert generation for all cameras; can be overridden per-camera." = "فعال یا غیرفعال کردن تولید هشدار برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    "Enable or disable detection events for all cameras; can be overridden per-camera." = "فعال یا غیرفعال کردن رویدادهای تشخیص برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    # snapshots
    "Settings for API-generated snapshots of tracked objects for all cameras; can be overridden per-camera." = "تنظیمات عکس‌های فوری تولیدشده توسط API از اشیاء ردیابی‌شده برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    "Enable or disable saving snapshots for all cameras; can be overridden per-camera." = "فعال یا غیرفعال کردن ذخیره عکس‌های فوری برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    # timestamp_style
    "Styling options for in-feed timestamps applied to debug view and snapshots." = "گزینه‌های استایل‌دهی برای مهرهای زمانی درون فید اعمال‌شده روی نمای اشکال‌زدایی و عکس‌های فوری."
    # audio_transcription
    "Enable or disable automatic audio transcription for all cameras; can be overridden per-camera." = "فعال یا غیرفعال کردن رونویسی خودکار صدا برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    "Transcription language" = "زبان رونویسی"
    "Language code used for transcription/translation (for example 'en' for English). See https://whisper-api.com/docs/languages/ for supported language codes." = "کد زبان مورد استفاده برای رونویسی/ترجمه (مثلاً 'en' برای انگلیسی). برای کدهای زبان پشتیبانی‌شده به https://whisper-api.com/docs/languages/ مراجعه کنید."
    "Transcription device" = "دستگاه رونویسی"
    "Device key (CPU/GPU) to run the transcription model on. Only NVIDIA CUDA GPUs are currently supported for transcription." = "کلید دستگاه (CPU/GPU) برای اجرای مدل رونویسی. در حال حاضر فقط GPUهای NVIDIA CUDA برای رونویسی پشتیبانی می‌شوند."
    "Model size" = "اندازه مدل"
    "Model size to use for offline audio event transcription." = "اندازه مدل برای استفاده در رونویسی رویداد صوتی آفلاین."
    # classification
    "Object classification" = "طبقه‌بندی اشیاء"
    "Settings for classification models used to refine object labels or state classification." = "تنظیمات مدل‌های طبقه‌بندی برای اصلاح برچسب‌های اشیاء یا طبقه‌بندی وضعیت."
    "Bird classification config" = "پیکربندی طبقه‌بندی پرندگان"
    "Settings specific to bird classification models." = "تنظیمات خاص مدل‌های طبقه‌بندی پرندگان."
    "Bird classification" = "طبقه‌بندی پرندگان"
    "Enable or disable bird classification." = "فعال یا غیرفعال کردن طبقه‌بندی پرندگان."
    "Minimum score" = "حداقل امتیاز"
    "Minimum classification score required to accept a bird classification." = "حداقل امتیاز طبقه‌بندی مورد نیاز برای پذیرش طبقه‌بندی پرنده."
    "Custom Classification Models" = "مدل‌های طبقه‌بندی سفارشی"
    "Configuration for custom classification models used for objects or state detection." = "پیکربندی مدل‌های طبقه‌بندی سفارشی برای اشیاء یا تشخیص وضعیت."
    "Enable model" = "فعال کردن مدل"
    "Enable or disable the custom classification model." = "فعال یا غیرفعال کردن مدل طبقه‌بندی سفارشی."
    "Model name" = "نام مدل"
    "Identifier for the custom classification model to use." = "شناسه مدل طبقه‌بندی سفارشی برای استفاده."
    "Score threshold" = "آستانه امتیاز"
    "Score threshold used to change the classification state." = "آستانه امتیاز مورد استفاده برای تغییر وضعیت طبقه‌بندی."
    "Save attempts" = "ذخیره تلاش‌ها"
    "How many classification attempts to save for recent classifications UI." = "تعداد تلاش‌های طبقه‌بندی برای ذخیره در رابط کاربری طبقه‌بندی‌های اخیر."
    "Classify objects" = "طبقه‌بندی اشیاء"
    "List of object types to run object classification on." = "فهرست انواع اشیاء برای اجرای طبقه‌بندی اشیاء."
    "Classification type" = "نوع طبقه‌بندی"
    "Classification type applied: 'sub_label' (adds sub_label) or other supported types." = "نوع طبقه‌بندی اعمال‌شده: 'sub_label' (افزودن sub_label) یا سایر انواع پشتیبانی‌شده."
    "Classification cameras" = "دوربین‌های طبقه‌بندی"
    "Per-camera crop and settings for running state classification." = "برش و تنظیمات به ازای هر دوربین برای اجرای طبقه‌بندی وضعیت."
    "Classification crop" = "برش طبقه‌بندی"
    "Crop coordinates to use for running classification on this camera." = "مختصات برش برای استفاده در اجرای طبقه‌بندی روی این دوربین."
    "Run on motion" = "اجرا هنگام حرکت"
    "If true, run classification when motion is detected within the specified crop." = "اگر درست باشد، طبقه‌بندی هنگام تشخیص حرکت در برش مشخص‌شده اجرا می‌شود."
    "Classification interval" = "بازه طبقه‌بندی"
    "Interval (seconds) between periodic classification runs for state classification." = "بازه (ثانیه) بین اجراهای دوره‌ای طبقه‌بندی برای طبقه‌بندی وضعیت."
    # semantic_search
    "Settings for Semantic Search which builds and queries object embeddings to find similar items." = "تنظیمات جستجوی معنایی که جاسازی‌های اشیاء را ساخته و جستجو می‌کند تا موارد مشابه را پیدا کند."
    "Enable semantic search" = "فعال کردن جستجوی معنایی"
    "Enable or disable the semantic search feature." = "فعال یا غیرفعال کردن ویژگی جستجوی معنایی."
    "Reindex on startup" = "بازنمایه‌سازی در شروع"
    "Trigger a full reindex of historical tracked objects into the embeddings database." = "راه‌اندازی بازنمایه‌سازی کامل اشیاء ردیابی‌شده تاریخی در پایگاه داده جاسازی‌ها."
    "Semantic search model or GenAI provider name" = "مدل جستجوی معنایی یا نام ارائه‌دهنده GenAI"
    "The embeddings model to use for semantic search (for example 'jinav1'), or the name of a GenAI provider with the embeddings role." = "مدل جاسازی برای استفاده در جستجوی معنایی (مثلاً 'jinav1') یا نام ارائه‌دهنده GenAI با نقش جاسازی."
    "Select model size; 'small' runs on CPU and 'large' typically requires GPU." = "انتخاب اندازه مدل؛ 'small' روی CPU اجرا می‌شود و 'large' معمولاً به GPU نیاز دارد."
    "Device" = "دستگاه"
    "This is an override, to target a specific device. See https://onnxruntime.ai/docs/execution-providers/ for more information" = "این یک لغو است برای هدف‌گیری دستگاه خاص. برای اطلاعات بیشتر به https://onnxruntime.ai/docs/execution-providers/ مراجعه کنید"
    # face_recognition
    "Settings for face detection and recognition for all cameras; can be overridden per-camera." = "تنظیمات تشخیص و شناسایی چهره برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    "Enable or disable face recognition for all cameras; can be overridden per-camera." = "فعال یا غیرفعال کردن شناسایی چهره برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    "Model size to use for face embeddings (small/large); larger may require GPU." = "اندازه مدل برای استفاده در جاسازی چهره (small/large)؛ مدل بزرگ‌تر ممکن است به GPU نیاز داشته باشد."
    "Unknown score threshold" = "آستانه امتیاز ناشناخته"
    "Distance threshold below which a face is considered a potential match (higher = stricter)." = "آستانه فاصله که زیر آن یک چهره به‌عنوان تطابق بالقوه در نظر گرفته می‌شود (بالاتر = سخت‌گیرانه‌تر)."
    "Detection threshold" = "آستانه تشخیص"
    "Minimum detection confidence required to consider a face detection valid." = "حداقل اطمینان تشخیص مورد نیاز برای در نظر گرفتن تشخیص چهره معتبر."
    "Recognition threshold" = "آستانه شناسایی"
    "Face embedding distance threshold to consider two faces a match." = "آستانه فاصله جاسازی چهره برای در نظر گرفتن دو چهره به‌عنوان تطابق."
    "Minimum faces" = "حداقل چهره‌ها"
    "Minimum number of face recognitions required before applying a recognized sub-label to a person." = "حداقل تعداد شناسایی‌های چهره مورد نیاز قبل از اعمال یک زیربرچسب شناسایی‌شده روی شخص."
    "Number of face recognition attempts to retain for recent recognition UI." = "تعداد تلاش‌های شناسایی چهره برای نگهداری در رابط کاربری شناسایی اخیر."
    "Blur confidence filter" = "فیلتر اطمینان تاری"
    "Adjust confidence scores based on image blur to reduce false positives for poor quality faces." = "تنظیم امتیازهای اطمینان بر اساس تاری تصویر برای کاهش مثبت‌های کاذب برای چهره‌های با کیفیت پایین."
    # lpr
    "Enable or disable license plate recognition for all cameras; can be overridden per-camera." = "فعال یا غیرفعال کردن تشخیص پلاک خودرو برای همه دوربین‌ها؛ قابل لغو به ازای هر دوربین."
    "Model size used for text detection/recognition. Most users should use 'small'." = "اندازه مدل مورد استفاده برای تشخیص/شناسایی متن. اکثر کاربران باید از 'small' استفاده کنند."
    "Detection confidence threshold to begin running OCR on a suspected plate." = "آستانه اطمینان تشخیص برای شروع اجرای OCR روی یک پلاک مشکوک."
    "Confidence threshold required for recognized plate text to be attached as a sub-label." = "آستانه اطمینان مورد نیاز برای پیوست متن پلاک شناسایی‌شده به‌عنوان زیربرچسب."
    "Min plate length" = "حداقل طول پلاک"
    "Minimum number of characters a recognized plate must contain to be considered valid." = "حداقل تعداد نویسه‌هایی که یک پلاک شناسایی‌شده باید داشته باشد تا معتبر در نظر گرفته شود."
    "Plate format regex" = "رجکس قالب پلاک"
    "Optional regex to validate recognized plate strings against an expected format." = "رجکس اختیاری برای اعتبارسنجی رشته‌های پلاک شناسایی‌شده در برابر قالب مورد انتظار."
    "Match distance" = "فاصله تطابق"
    "Number of character mismatches allowed when comparing detected plates to known plates." = "تعداد عدم تطابق‌های نویسه مجاز هنگام مقایسه پلاک‌های تشخیص‌داده‌شده با پلاک‌های شناخته‌شده."
    "Known plates" = "پلاک‌های شناخته‌شده"
    "List of plates or regexes to specially track or alert on." = "فهرست پلاک‌ها یا رجکس‌ها برای ردیابی یا هشدار ویژه."
    "Save debug plates" = "ذخیره پلاک‌های اشکال‌زدایی"
    "Save plate crop images for debugging LPR performance." = "ذخیره تصاویر برش پلاک برای اشکال‌زدایی عملکرد LPR."
    "Replacement rules" = "قوانین جایگزینی"
    "Regex replacement rules used to normalize detected plate strings before matching." = "قوانین جایگزینی رجکس برای نرمال‌سازی رشته‌های پلاک تشخیص‌داده‌شده قبل از تطابق."
    "Regex pattern" = "الگوی رجکس"
    "Replacement string" = "رشته جایگزینی"
    # camera_groups
    "Camera groups" = "گروه‌های دوربین"
    "Configuration for named camera groups used to organize cameras in the UI." = "پیکربندی گروه‌های دوربین نام‌گذاری‌شده برای سازماندهی دوربین‌ها در رابط کاربری."
    "Camera list" = "فهرست دوربین‌ها"
    "Array of camera names included in this group." = "آرایه‌ای از نام‌های دوربین موجود در این گروه."
    "Group icon" = "آیکون گروه"
    "Icon used to represent the camera group in the UI." = "آیکون مورد استفاده برای نمایندگی گروه دوربین در رابط کاربری."
    "Sort order" = "ترتیب مرتب‌سازی"
    "Numeric order used to sort camera groups in the UI; larger numbers appear later." = "ترتیب عددی برای مرتب‌سازی گروه‌های دوربین در رابط کاربری؛ اعداد بزرگ‌تر بعداً ظاهر می‌شوند."
    # profiles
    "Profiles" = "پروفایل‌ها"
    "Named profile definitions with friendly names. Camera profiles must reference names defined here." = "تعاریف پروفایل نام‌گذاری‌شده با نام‌های دوستانه. پروفایل‌های دوربین باید به نام‌های تعریف‌شده در اینجا ارجاع دهند."
    "Friendly name" = "نام دوستانه"
    "Display name for this profile shown in the UI." = "نام نمایشی این پروفایل در رابط کاربری."
    # active_profile
    "Active profile" = "پروفایل فعال"
    "Currently active profile name. Runtime-only, not persisted in YAML." = "نام پروفایل فعال فعلی. فقط در زمان اجرا، در YAML ذخیره نمی‌شود."
    # camera_mqtt
    "MQTT" = "MQTT"
    "MQTT image publishing settings." = "تنظیمات انتشار تصویر MQTT."
    "Send image" = "ارسال تصویر"
    "Enable publishing image snapshots for objects to MQTT topics for this camera." = "فعال‌سازی انتشار عکس‌های فوری اشیاء به موضوعات MQTT برای این دوربین."
    "Add timestamp" = "افزودن مهر زمانی"
    "Overlay a timestamp on images published to MQTT." = "قرار دادن مهر زمانی روی تصاویر منتشرشده به MQTT."
    "Add bounding box" = "افزودن کادر مرزی"
    "Draw bounding boxes on images published over MQTT." = "رسم کادرهای مرزی روی تصاویر منتشرشده از طریق MQTT."
    "Crop image" = "برش تصویر"
    "Crop images published to MQTT to the detected object's bounding box." = "برش تصاویر منتشرشده به MQTT به کادر مرزی شیء تشخیص‌داده‌شده."
    "Image height" = "ارتفاع تصویر"
    "Height (pixels) to resize images published over MQTT." = "ارتفاع (پیکسل) برای تغییر اندازه تصاویر منتشرشده از طریق MQTT."
    "Required zones" = "مناطق مورد نیاز"
    "Zones that an object must enter for an MQTT image to be published." = "مناطقی که یک شیء باید وارد شود تا یک تصویر MQTT منتشر شود."
    "JPEG quality" = "کیفیت JPEG"
    "JPEG quality for images published to MQTT (0-100)." = "کیفیت JPEG برای تصاویر منتشرشده به MQTT (0-100)."
    # camera_ui
    "Camera UI" = "رابط کاربری دوربین"
    "Display ordering and visibility for this camera in the UI. Ordering affects the default dashboard. For more granular control, use camera groups." = "ترتیب نمایش و قابلیت مشاهده این دوربین در رابط کاربری. ترتیب روی داشبورد پیش‌فرض تأثیر می‌گذارد. برای کنترل دقیق‌تر از گروه‌های دوربین استفاده کنید."
    "UI order" = "ترتیب رابط کاربری"
    "Numeric order used to sort the camera in the UI (default dashboard and lists); larger numbers appear later." = "ترتیب عددی برای مرتب‌سازی دوربین در رابط کاربری (داشبورد پیش‌فرض و فهرست‌ها)؛ اعداد بزرگ‌تر بعداً ظاهر می‌شوند."
    "Show on Live dashboard" = "نمایش در داشبورد پخش زنده"
    "Toggle whether this camera is visible on the default All Cameras live dashboard. The camera remains available everywhere else in the UI, including camera groups and settings." = "مشخص کنید که آیا این دوربین در داشبورد پیش‌فرض همه دوربین‌های زنده قابل مشاهده باشد. دوربین در همه جای رابط کاربری از جمله گروه‌های دوربین و تنظیمات در دسترس باقی می‌ماند."
    "Show in review" = "نمایش در بازبینی"
    "Toggle whether this camera is visible in review (the review page and its camera filter, motion review, and the history view)." = "مشخص کنید که آیا این دوربین در بازبینی قابل مشاهده باشد (صفحه بازبینی و فیلتر دوربین آن، بازبینی حرکت و نمای تاریخچه)."
    # onvif
    "ONVIF profile" = "پروفایل ONVIF"
    "Specific ONVIF media profile to use for PTZ control, matched by token or name. If not set, the first profile with valid PTZ configuration is selected automatically." = "پروفایل رسانهٔ ONVIF خاص برای کنترل PTZ، مطابقت‌شده با توکن یا نام. اگر تنظیم نشود، اولین پروفایل با پیکربندی PTZ معتبر به‌طور خودکار انتخاب می‌شود."
    # record export
    "Maximum concurrent exports" = "حداکثر خروجی‌های همزمان"
    "Maximum number of export jobs to process at the same time." = "حداکثر تعداد کارهای خروجی که همزمان پردازش می‌شوند."
    "Chapter metadata to embed in exported recordings" = "فرادادهٔ فصل برای جاسازی در ضبط‌های خروجی‌گرفته‌شده"
}

# Read the file
$filePath = (Resolve-Path "web\public\locales\fa\config\global.json").Path
$content = [System.IO.File]::ReadAllText($filePath, [System.Text.UTF8Encoding]::new($false))

# Replace each English value with Persian translation
$replaced = 0
foreach ($en in $translations.Keys) {
    $fa = $translations[$en]
    # Escape for JSON string matching
    $enEscaped = $en -replace '\\', '\\\\' -replace '"', '\"'
    $faEscaped = $fa -replace '\\', '\\\\' -replace '"', '\"'
    
    if ($content.Contains($enEscaped)) {
        $content = $content.Replace($enEscaped, $faEscaped)
        $replaced++
    }
}

# Write back
[System.IO.File]::WriteAllText($filePath, $content, [System.Text.UTF8Encoding]::new($false))
Write-Output "Replaced $replaced values"
